

# This file was *autogenerated* from the file TU.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_65 = Integer(65); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_100 = Integer(100)
from sage.crypto.sbox import SBox
import itertools
n = _sage_const_8 
c = _sage_const_65 
gf = GF(_sage_const_2 **(n-_sage_const_1 ))

binaryToInt = lambda binaryVector: int("".join(str(x) for x in binaryVector), _sage_const_2 )
get_bin = lambda x, n: list(map(lambda x: int(x), list(format(x, 'b').zfill(n))))

def T(x1, x2, c, n):
	gf_x1 = gf.fetch_int(binaryToInt(x1))
	if gf_x1 == _sage_const_0 :
		return gf_x1
	reverse_x1 = gf_x1**(-_sage_const_1 )
	return reverse_x1 * gf.fetch_int(c)**x2

def U(f, x2, x1):
	return (f(x1) + x2) % _sage_const_2 

def F(x):
	x1 = x[:-_sage_const_1 ]
	x2 = x[-_sage_const_1 ]
	T_res = get_bin(T(x1, x2, c, n).integer_representation(), n)
	U_res = [U(lambda x: sum(x)%_sage_const_2 , x2, T_res)]
	return T_res + U_res

combinations = [list(i) for i in itertools.product([_sage_const_0 , _sage_const_1 ], repeat=n)]

for i in range(_sage_const_1 ,_sage_const_100 ):
	c = i
	F_results = list(map(lambda x: F(x), combinations))
	s = map(lambda x: binaryToInt(x), F_results)
	sbox = SBox(s)
	print("Fixed points: ", sbox.fixed_points())
	print("Min degree: ", sbox.min_degree())
	print("Polynimials lenght: ", len(sbox.polynomials()))
	print("sigma: ", sbox.differential_uniformity())
	print("c = ", c)
	print("tr(c): ", gf.fetch_int(c).trace())
	print("tr(c^-1): ", (gf.fetch_int(c)**(-_sage_const_1 )).trace())

